version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: increment-postgres55
    ports:
      - "5495:5432"
    environment:
      POSTGRES_DB: employee_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: increment-backend55
    ports:
      - "3095:3095"
    environment:
      DB_USER: postgres
      DB_HOST: postgres
      DB_NAME: employee_portal
      DB_PASSWORD: admin123
      DB_PORT: 5432
    depends_on:
      - postgres

  employee-increment:
    build: ./Employee-Increment
    container_name: employee-increment55
    ports:
      - "8191:80"
    depends_on:
      - backend

  hr-increment:
    build: ./HR-Increment
    container_name: hr-increment55
    ports:
      - "8192:80"
    depends_on:
      - backend

volumes:
  db_data:

